### ISSUE TITLE
Ways to evaluate if user abandoned the tour or left incomplete

### ISSUE THREAD

**Issue by k10world** [linkedin/hopscotch#120]
My team was thinking about the ways to evaluate - if the user is navigating away from the page where tour is currently running and the next page is not the next in the workflow.

Any ideas what APIs of framework will help?

I know for one is hopscotch.getState().

Has anyone come across such a scenario.
I saw this implemented in Google Adwords.

**Comment by zimmi88** [comment]
`hopscotch.getState()` seems like a reasonable approach here to determine if a tour was running on the previous page after hopping to a new page. If it's not a multipage tour, you could make the assumption that any navigation away from the page isn't in the flow and bind an event to `window.onbeforeunload`. Otherwise, you'd need some code on the other page(s) that looks at `hopscotch.getState()` and catches that the new page is, or isn't, in the tour's flow.

I hope this helps!
