### ISSUE TITLE
isTourBubble and showNumber: BUG ? (and an ugly workaround)

### ISSUE THREAD

**Issue by tivnet** [linkedin/hopscotch#131]
There are two undocumented settings: `showNumber` and `isTourBubble`.

I'd expect that `no-number` class should be added when `showNumber` is `false`. However, it's not the case:

```js
      opt = {
        ...
        showNumber:     true,
        isTourBubble:   true
      };
      ...

      //Apply classes to bubble. Add "animated" for fade css animation
      el.className = 'hopscotch-bubble animated';
      if (!opt.isTourBubble) {
        utils.addClass(el, 'hopscotch-callout no-number');
      }
```

**Comment by zimmi88** [comment]
Hi @tivnet, thanks for the info!

Huh, so it looks like there's only one reference to `showNumber` in hopscotch.js (that's it in the code you provided above) and it does a whole lot of nothing. I'm guessing the code that consumed this field got refactored away when we switched over to templates. =/

I'm actually not sure if I'm sold on keeping this option around, though. On one hand, this is something that an end user could update their template to read as `customData` and I'm not sure how useful this is to have as a core config option. On the other hand, I can see how altering `bubble-default` (or writing a new template), then rebuilding a custom version of Hopscotch might be overkill.

(Side note: Might be useful to publish a version of Hopscotch without `bubble-default`, for cases where end users don't intend to use `bubble-default` anyway.)

As for `isTourBubble`, I've got the feeling this isn't intended as a public option. Since both `Hopscotch` and `HopscotchCalloutManager` utilize `HopscotchBubble` this is how the two are distinguished. But `HopscotchBubble` shouldn't be in the business of handling business logic like this, anyway, so it should probably go away too.

I hope this helps! I'd love to hear any thoughts on whether there might be any value in keeping `showNumber` around... any other opinions on the matter?

**Comment by zimmi88** [comment]
I've rolled the above suggestions into issue #144. For now, I'm going to close this issue as a duplicate. Thanks!

**Comment by NhatHo** [comment]
I'm currently having this problem as well, my would around is also to use css to override the default template in hopscotch, which is not a clean and safe solution.

Instead of removing showNumber, can you keep that option around but extend on it? 
showNumber should be true by default, but if user decides to set it to false:

```javascript
if(!opt.showNumber) {
    utils.addClass(el, 'no-number');
}
```

I'm not sure if that piece of code would work, but something like that would help a great deal.
