### ISSUE TITLE
IE 9 & 10 breaks with appendChild of undefined error

### ISSUE THREAD

**Issue by Sivakumaresan** [linkedin/hopscotch#172]
![ieissue1](https://cloud.githubusercontent.com/assets/4970666/7385474/91c77f2a-ee64-11e4-8a78-a9f652da1b05.jpg)
I am getting above error when I test my application in lower versions of IE, document ready is not fired as expected. Can we have a fix for this?

**Comment by zimmi88** [comment]
Thanks for the info, @Sivakumaresan! Though, seems odd we'd end up in this state, at least if I'm understanding the Hopscotch code correctly. `utils.documentIsReady()` should only report true if `document.readyState` is `interactive` or `complete`... and so far as I can tell `document.body` should exist if that's the case (`document.body` doesn't exist until the browser's done parsing the document). Though, I might be missing something... maybe we need to specifically check for `complete` instead of also accepting `interactive`?

Do you have a sample use case that duplicates this behavior? You mention IE 9 and 10 specifically... are those the only two versions where you're seeing this issue?

**Comment by Sivakumaresan** [comment]
I am using IE 10, when the  `document.readyState` is  `interactive` and IE still have the `document.body` as `null`. As you mentioned we should probably look only for `complete`. Yes this issue is only with IE 9 and 10, other browsers works great.
