### ISSUE TITLE
Feature : Callback after Rendering Step Pop-Up. ( onRenderingCompleted )

### ISSUE THREAD

**Issue by rustemtr** [linkedin/hopscotch#184]
Hi guys,

I'm trying to put a step into a dropdown menu. I tried to toggle(open) dropdown menu in onShow callback of that step but onShow method fires before rendering occurs. When the rendering finishes, dropdown menu toggles back to closed state. 

I think I need someting like onRenderingCompleted event. I couldn't find a callback that fires after rendering occurs. 
Is there any easy way to extend that feature?
Thanks

**Comment by zimmi88** [comment]
Hi @rustemtr,

To clarify, is this regarding the rendering of the Hopscotch bubble for a given step/callout? From the latest code, the bubble should render before the `onShow` callback is invoked. (Line 1762, called in response to `bubble.render()` on line 1775)

If this isn't the case, we should take a closer look. What browser(s) are you seeing this behavior in? Also, is this within the context of a tour or is this a standalone `HopscotchCallout`?

**Comment by rustemtr** [comment]
Step 3 : 
![image](https://cloud.githubusercontent.com/assets/3941229/8159854/5d9f4960-1373-11e5-84d9-f7a863f209bf.png)

Step 4 : 
![image](https://cloud.githubusercontent.com/assets/3941229/8159863/6d121a94-1373-11e5-9a53-7a77f3272b02.png)

Hi again,

What I'm trying to achieve is to go from step 3 to step 4 ( within the context of a tour. Please see attached images. )
I think I need to open the dropdown menu programatically( simple Jquery code that adds the css class 'open' to ul tag ), but I couldn't find the correct place to put that code. 

I tried to put my Jquery code inside onShow method of step 4, however it didn't work.

I debugged the code and examined that onShow method fires before the step 4 bubble appears on the screen, 
(debugged with Chrome ( v43.0.2357.124) Developer Tools on Win 8.1 )
1. clicked next on step 3
2. onShow callback of step 4 fired
3. Jquery code inside onShow method opened the dropdown
4. dropdown closed before the step 4 bubble appeared on the screen.

What surprised me was that when I click prev button of step 5, it works like a charm. ( I don't have any code for onNext method of step 3 and onPrev method of step 5 )

Hope it's clear now :pray:

**Comment by zimmi88** [comment]
Hmm... the default CSS that ships with Hopscotch includes animations to fade in the bubble, but the bubble should exist in the DOM at the point the `onShow` callback is invoked. There shouldn't be any logic in Hopscotch that would cause the dropdown to close... I'm guessing the intent of the class is to keep the dropdown open even if there's other logic that says otherwise?

Another hypothesis... if the tour is run again on the same page (without refreshing), or alternatively if you apply the class via other means before starting the tour, does applying the class during the tour work ok? Might be a matter of the dropdown code tripping up on the first invocation.
