### ISSUE TITLE
Documentation for the tour target is incorrect 

### ISSUE THREAD

**Issue by mathonsunday** [linkedin/hopscotch#198]
The documentation for the tour target is incorrect. 

In my tour I had:
```javascript
target: document.querySelector("[id *= 'campaignMenu']"),
```
This failed silently. `document.querySelector` gives a DOM element which according to the documentation should work.

What worked was using a selector instead:
```javascript
target: "[id *= 'campaignMenu']",
```
Which made sense when I looked at the source code.

**Comment by kate2753** [comment]
@mathonsunday it's acceptable to use both approaches. As per [documentation](http://linkedin.github.io/hopscotch/#all-step-options)  target config is "id of the target DOM element or DOM element itself".

Passing in selector instead of the element itself defers element lookup until right before the step is shown. You have to be careful about using `document.querySelector`, it will execute search for the element immediately before invoking `startTour` function. So you need to make sure that element exists when `document.querySelector` is called.
