### ISSUE TITLE
Getting error TypeError: i.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by ajinkyagadewar** [linkedin/hopscotch#207]
Unable to understand why this error is coming:
...de-in-up fade-in-left fade-in-right"),d=i.getBoundingClientRect(),h=a.isRtl?d.ri...

I am using target as shown below:
target: document.querySelectorAll('a[href*="tab-1-0"]'),

**Comment by eoneill** [comment]
Try using `querySelector` instead of `querySelectorAll`.

`querySelectorAll` returns a `NodeList` collection (e.g. _all_ of the nodes that match) and calling `getBoundingClientRect` on a collection doesn't really make sense :)

Whereas `querySelector` returns the first matching node.

Alternately, you can grab a specific node from the `NodeList` collection. e.g. if you want to target the 4th node, you would do something like `document.querySelectorAll(...)[3]`.

**Comment by zimmi88** [comment]
Given @eoneill's feedback should resolve this issue, I'm going to mark this as closed. Thanks!
