### ISSUE TITLE
Passing a dynamic variable doesn't work for callouts

### ISSUE THREAD

**Issue by balasivagnanam** [linkedin/hopscotch#210]
Hi, Thanks for this awesome framework.

I am using this to get callouts on clicking at different points in my page.

Here is my code, but for some reason, the console.log prints Error: Must specify a callout id.

I am trying to create multiple configurations for the callouts and call the respective callout based on the click point. My click points are also given the same id as the one I use in the target of the callouts.

```
//initialise and get the
function initInstruction(){
  var hopscotch_title = {
    id: "hopscotch_title",
      title: "My Header",
      content: "This is the header of my page.",
      target: "hopscotch_title",
      placement: "top"
  };
  var hopscotch_subtitle = {
    id: "hopscotch_subtitle",
      title: "My Header",
      content: "This is the header of my page.",
      target: "hopscotch_subtitle",
      placement: "top"
  };
  console.log("functionc call");
  activateSpots(hopscotch_title, hopscotch_subtitle);
};
// to activate the spots in the html
function activateSpots(tour, tour1){
    console.log("activate call");
      console.log(tour.target);
      item = tour.target;
      $("#" + item).addClass("hotspot");
      console.log(tour1.target);
      item = tour1.target;
      $("#" + item).addClass("hotspot");
}
// to deactivate the spots in the html
function deactivateSpots(){
      $(".hotspot").removeClass("hotspot");
}

// to listen for click events and show callouts for the spots in the html
$(document).on('click', ".hotspot", function() {
    var liId = $(this).attr("id");
    console.log(liId);
    console.log(liId.length);
    var newStr = $.trim(liId);
    console.log(newStr);
    var calloutMgr = hopscotch.getCalloutManager();
    calloutMgr.createCallout(newStr);
});

```

**Comment by balasivagnanam** [comment]
it works when i do this...
$(document).on('click', ".hotspot", function() {
    var liId = $(this).attr("id");
    console.log(liId);
    console.log(liId.length);
    var newStr = $.trim(liId);
    console.log(newStr);
    var calloutMgr = hopscotch.getCalloutManager();
    calloutMgr.createCallout({
      id: "hopscotch_title",
        title: "My Header",
        content: "This is the header of my page.",
        target: "hopscotch_title",
        placement: "top"
    });
});

but I have many call outs in a page and I have many pages so I am looking to write a common script.

**Comment by balasivagnanam** [comment]
sorry about that.. some problem with passing the name of the callout object as a variable and I was passing the name instead of object.

```
  calloutMgr.createCallout(window[newStr]);
```

I am currently using this, is there a better way to structure this scenario.
Sorry I am a very beginner.

**Comment by zimmi88** [comment]
Cool, glad to see you were able to get this working! I think the general strategy you have is reasonable... you might consider the following refactoring options...
- Instead of creating a new global variable for each callout, you could have one object instead you add key/object pairs to.
- Or, alternatively, depending on how much of the config needs to change for each callout, the keys that change between each callout could be data attributes on the elements themselves, which are then read in the callback for your click event and used to construct a config that's passed to `createCallout()`.

Given this isn't a feature request or bug related to the Hopscotch framework, I'm marking this as closed. I hope this helps!
