### ISSUE TITLE
Deprecated gradient warnings

### ISSUE THREAD

**Issue by matthewmueller** [linkedin/hopscotch#232]
Looks like the gradient syntax changed a bit:

```
autoprefixer: /tmp/build/node_modules/hopscotch/dist/css/hopscotch.css:290:3: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".

autoprefixer: /tmp/build/node_modules/hopscotch/dist/css/hopscotch.css:299:3: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".

autoprefixer: /tmp/build/node_modules/hopscotch/dist/css/hopscotch.css:311:3: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".

autoprefixer: /tmp/build/node_modules/hopscotch/dist/css/hopscotch.css:320:3: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
```

**Comment by kate2753** [comment]
Will be fixed with pull request #244

**Comment by kate2753** [comment]
Resolved with #244

**Comment by iamkevinv** [comment]
Hmmm... really wish this was in the released build i'm pulling with NPM as i've got the less files directly pulled into my own build which also gets processed with autoprefixer in the gulp pipe.
Is the gh72 branch the target for the maintenance release on the 0.2.x path or is that wishful seeing the currently allocated ES6 Refresh milestone against this issue @zimmi88 @kate2753? 
Looking at the actual commit it's pretty ripe for a backport to the maintenance release and has nothing to do with ES6 and the like... or is that me just being presumptuous now :-)

**Comment by zimmi88** [comment]
gh72 is the branch for the ES6 Refresh milestone. Despite the naming, that milestone is where we're tracking a number of cleanup items, including some CSS and template refactoring. Sorry for the confusion.

Is this completely breaking gulp builds and/or the user experience? If so, IMO, we should drop these gradients from master.

**Comment by iamkevinv** [comment]
Thanks for the info - i was using my own gulp build stack and importing your source less files, which, once run through plumber and the autoprefixer, caused warnings and for some reason decided to pause gulp processing from continuing. 

It drove me crazy for a few hours trying to work out why it would just sit there mid processing. I've since pulled in the less files to my own repo from the copies on gh72 and that has resolved the problem now. My usage/install setup is just using npm install and require('hopscotch') for my browserify build. That's running well, and in retrospect it was probably a silly idea for me to load your src less files into my build right out the node_modules directory anyway :-) ...but the gulp breakage was definitely a weird event.

I hope to be able to contribute to this project, as it's going to become a great part of my own 👍 
Assuming small new features are discouraged during this transition, or are they still encouraged?

Thanks!

**Comment by zimmi88** [comment]
It's not entirely silly, especially if you'd want to make customizations to a particular file while relying on the other core files. That said, building off of anything that isn't in dist is a wild west of things that could change or break at any time (though we'd try to avoid this).

For now, I'd recommend creating new issues for feature requests (provided an issue hasn't been created already). Unless it's a super small update, though, we likely won't pull in new features to the current `master` branch. Right now, the focus is to get `gh72` to feature parity with `master`, tackle some code cleanup items, and build out the Plugins API (so it's a lot easier to mix in features on a case-by-case basis).

**Comment by jfroffice** [comment]
We are still getting some warnings from __autoprefixer__ with the gradient syntax.

```
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
```

**Comment by zimmi88** [comment]
I don't see anything in the outputted CSS in the repo's dist folder that could be causing this, as far as I can tell. Is there a particular line that's throwing this error?
