### ISSUE TITLE
How to end view

### ISSUE THREAD

**Issue by srdavidsilva** [linkedin/hopscotch#251]
Hello,
Sorry for my ignorance.
I can implement the tour in my project, but I can not understand how to avoid it to start every time you appear.
I believe I can do as setting concluded in a cookie or something in the database, the problem is that my knowledge in js is very limited and I could not even make any call to a php after click the Done.
Very Thnks

**Comment by zimmi88** [comment]
Hi @srdavidsilva,

This question falls outside the scope of this issue tracker, as it involves integration with a specific use case rather than Hopscotch itself. But here's a couple of thoughts that might help...

- The only storage that Hopscotch creates itself is for tracking tours in progress, using session storage, or falling back to cookies if that's not available. If you want more longer-lived knowledge of whether a tour has been taken, you'll need to save it in a database (presuming you're showing tours to someone that's logged in to an account on your website) or your own key in local storage (won't carry over if the viewer changes browsers or clears local data).
- The `onEnd` callback for your tour is going to be the point at which you handle this logic. If it's saved in a database, you can make an XHR/AJAX call to a URL that you've implemented to save this info. If it's local storage, then you can save that key/value pair on the client side using JS.
- Once you are saving this information, you can add logic to your code that determines whether to start the tour (by invoking `hopscotch.startTour()`) based on whether the tour has been previously viewed.

I hope this helps! I'm going to close this issue since there's no action to be taken, but feel free to reply back if you're unsure about the general information above.
