### ISSUE TITLE
Support for multiple tours in single page.

### ISSUE THREAD

**Issue by padmarao123** [linkedin/hopscotch#268]
We can user two instances in single page but the problem exists because the local-storage name is set to static name called `hopscotch.tour.state` so one tour which state is set to step 3, this is automatically using by other tour in this case other tour is starting from the step 3. This may be avoided by giving the namespace as developer option.

**Comment by andrewnicols** [comment]
Hi @padmarao123,

Have you tried setting the cookieName? You can do so in the tour configuration by setting config.cookieName.

Not sure how this would work with multiple tours - I haven't tried.

**Comment by pavankumarkatakam** [comment]
I didnt see cookieName in the conig, i will give a try

**Comment by zimmi88** [comment]
As noted, setting the cookieName when switching tours is a reasonable way to keep state of multiple tours. Hopscotch by design forgets the previous tour when a new one is started, so your app's code will need to act as intermediary with setting the correct cookie name for the tour being launched before starting the tour.

I hope this helps!
