### ISSUE TITLE
Step by step guide to building a custom bubble template

### ISSUE THREAD

**Issue by j3tchy** [linkedin/hopscotch#278]
Hi, I was wondering if there are any resources which show how to create custom markup for the bubble?
I've read the README within `/src/tl` folder but I'm still having trouble creating a custom template.

Thanks.

**Comment by zimmi88** [comment]
The README is probably the most comprehensive documentation we have for templates at the moment. If you have a particular issue you're running into, I can try to help with that. Otherwise, we may end up dropping the JST compilation in the near future (though there will still be a mechanism by which you could declare a `render` method to generate bubble HTML).

I hope this helps!
