### ISSUE TITLE
extjs implementation

### ISSUE THREAD

**Issue by itayko** [linkedin/hopscotch#293]
Hi
Is there a way to apply this in Sencha Ext JS?
(https://www.sencha.com/products/extjs)

Thanks

**Comment by zimmi88** [comment]
I haven't worked with Ext JS before, so I'm not sure what the exact integration details would be. That said, Hopscotch is designed to work as a generic JS library aside other page code. Likely, you'll need to include hopscotch.js on the page alongside any application-specific code, then interact with Hopscotch from your application's code using the Hopscotch API.

I'll leave this issue open for a few days to see if anyone else in the community might have suggestions. However, since this doesn't appear to be an issue with the Hopscotch library, I'll close this after a few days.

I hope this helps!
